---
title: "ASA Directory of Statistical Consultants"
---


::: callout-note
This directory was last updated on `r Sys.Date()`. 

Please [report an issue](https://github.com/ASA-CNSL/consultant-directory-website/issues/new) if you experience unexpected or broken links. 

Listings can be updated or requested via [this form](https://docs.google.com/forms/d/e/1FAIpQLSdU__AWWWNNXsIw3cOwajCUwcNuPjK3u0vRXM9_tDnbm1nC0A/viewform?usp=dialog). Some entries have been migrated from the previous directory; these appear as [migrated] in the table below. Section members can update their listing via the preceding form.
:::

```{r setup, echo = FALSE, message = FALSE}
library(dplyr)
library(knitr)
library(DT)
library(googlesheets4)
library(htmltools)

# # Get project metadata
# # Get the build directory (defaults to _site)
# proj_info <- quarto::quarto_inspect()
# build_dir <- proj_info$project[["output-dir"]] %||% "_site"
# 
# str(proj_info)
# message("build_dir:\t", build_dir)

profile_target <- function(email, where=\(x) file.path("profile", x)) {
    sprintf(fmt="%s.html", sub("@", "_at_", email)) |> where()
  
}

```

```{r read-data, echo = FALSE, message = FALSE}

# path to current membership, need to get this hy Download to local from https://ww2.amstat.org/OfficerReports/index.cfm, available on leadership hub
path_to_current <- "../CNSL_ Section on Statistical Consulting_Current.xlsx"

# path to google form (need authentication, contact Ryan Peterson)
path_to_form_data <- 'https://docs.google.com/spreadsheets/d/1CKpngSWGC54YHUHwbOCyraWKOSkCoc4rzbvJWg3ZlqM/edit?usp=sharing'

# Read Section Membership Directory & form data 
current_members <- readxl::read_excel(path_to_current) %>% 
  rename(`ASA Member Number` = membership_Individual_LocalID, 
         expiration_date = membership_ExpirationDate) %>% 
  mutate(expiration_date = as.Date(expiration_date))


form_responses <- read_sheet(path_to_form_data) 

# will need to save and track some info for profile building
form_responses |> 
  select(`Email address (as you'd like it to appear)`, 
         `Name (as you'd like it to appear)`, 
         `In-person availability (if applicable, list city/state/region)`, 
         `Website URL (optional)`, 
         `Highest Degree`, 
         `Field of Degree`,
         `Typical consulting context`,
         Languages,
         `Area(s) of Expertise. Select up to 3.`,
         `Application Specialties (up to 3)`) |> 
  saveRDS("form_responses.RDS")

old_listings <- readxl::read_excel('../ASA Consultant Directory.xlsx')


```

```{r clean, echo = FALSE, message = FALSE}
form_responses <- form_responses %>% 
  rename("ASA Member Number" = "ASA Member Number (6 digit number)")

# clean member number 
if(!is.numeric(form_responses$`ASA Member Number`))
  warning("Fix form error in spreadsheet ASA Member Number")

form_responses$`ASA Member Number` <- as.numeric(form_responses$`ASA Member Number`)

form_responses <- form_responses %>% 
  filter(!grepl("Test", `Name (as you'd like it to appear)`))

# Add filter for timestamp within 365 days 
form_responses <- form_responses %>% 
  mutate(listing_age = difftime(Sys.time(), Timestamp, units = "days"),
         expiration_date = as.Date('2026-12-31') #TODO
         ) %>% 
  filter(listing_age <= 365)

# merge with existing members 
directory_members <- left_join(form_responses, current_members) %>% 
  mutate(active = expiration_date >= Sys.Date()) %>% 
  mutate(listing_age = difftime(Sys.time(), Timestamp, units = "days")) %>% 
  filter(listing_age <= 365) %>% 
  filter(!is.na(`ASA Member Number`)) %>% 
  group_by(`ASA Member Number`) %>% 
  filter(Timestamp == max(Timestamp)) %>% 
  ungroup()

# merge with existing members as of Jan 1 2026
directory_members <- current_members %>% 
  select(`ASA Member Number`, expiration_date) %>% 
  right_join(directory_members) %>% 
  mutate(active = expiration_date < "01/01/2026")


directory_members <-directory_members %>% 
  filter(grepl("consent", `Consent & Acknowledgement`)) %>% 
  filter(grepl("acknowledge", `Consent & Acknowledgement`))
  
# nrow(directory_members) # Number of forms matching currently-active Section members 

# Add filter for validated

listings <- directory_members %>% 
  select(Name = `Name (as you'd like it to appear)`, 
         Expertise = `Area(s) of Expertise. Select up to 3.`,
         Specialty = `Application Specialties (up to 3)`, 
         Mode = `Consulting Mode`, 
         Location = `In-person availability (if applicable, list city/state/region)`,
         Languages = Languages,
         Contact = `Email address (as you'd like it to appear)`,
         Website = `Website URL (optional)`) %>% 
  mutate(Links = paste0('<a href="mailto:', Contact, '">email</a>')) %>% 
  mutate(Website = gsub("https://", "", Website)) %>% 
  mutate(Links = ifelse(!is.na(Website), 
                        paste0(Links, '; <a href="https://', Website, '">website</a>'), Links)) %>% 
  mutate(Name = mapply(\(x,y){as.character(a(href=profile_target(x), y))}, Contact, Name)) %>% 
  select(-Contact, -Website, -Mode)

## TO DO
# ensure Make sure only 3 expertise and specialties selected
reduce_to_3 <- function(x) {
  expertises <- strsplit(x, ", ")
  sapply(expertises, function(y) {
    if(length(y) < 3) 
      return(paste(y, collapse = ", "))
    paste(y[1:3], collapse = ", ")
  })
}

listings$Expertise <- reduce_to_3(listings$Expertise)
listings$Specialty <- reduce_to_3(listings$Specialty)


# migrate old ones (only do once in 2026, then these will require new form submission in 2027)
old_listings$`ASA Member Number` <- old_listings$ASAID

# Migrate?
# intersect(old_listings$`ASA Member Number`, current_members$`ASA Member Number`) %>% 
#   length()

to_migrate <- current_members %>% 
  inner_join(old_listings) %>% 
  filter(expiration_date > "2025-12-31")

state_abb_to_name <- function(x) {
  y <- rep(NA_character_, length(x))
  
  for(i in 1:length(x)) {
    if(!is.na(x[i])) {
      state <- state.name[state.abb %in% x[i]]
      if(!length(state))
        state <- ""
      y[i] <- state
    }
       
  }
  y
}

listings_to_migrate <- to_migrate %>% 
  group_by(`ASA Member Number`) %>% 
  slice(1) %>% 
  ungroup() %>% 
  mutate(
    Name = paste0(FirstName, " ", LastName),
    Expertise = "[migrated]", 
    Specialty = "[migrated]", 
    Location = state_abb_to_name(State)
    ) %>% 
  mutate(Links = paste0('<a href="mailto:', membership_Individual_EmailAddress, '">email</a>')) %>% 
  mutate(MoreInfo = gsub("https://", "", MoreInfo)) %>% 
  mutate(Links = ifelse(!is.na(MoreInfo), 
                        paste0(Links, '; <a href="https://', MoreInfo, '">website</a>'), Links)) %>% 
  select(Name:Links)

# Only first three expertise listed 
listings <- bind_rows(arrange(listings, Name), listings_to_migrate) 

listings %>% 
  datatable(options=list(pageLength=25, autoWidth=TRUE), rownames=FALSE, 
            escape = FALSE, filter = "top")
```
